### ISSUE TITLE
irhythmtestdataset

### ISSUE THREAD

**Issue by speculaas** [elenamer/ecg_classification_DL#6]
Dear Ms. Elena,

Thanks for the repo!

I am trying the explore.py (https://github.com/elenamer/ecg_classification_DL/blob/main/explore.py) and get this error: 

from datasets.irhythmtestdataset import iRhythmTestDataset
ModuleNotFoundError: No module named 'datasets.irhythmtestdataset'

So I am wondering if you missed this dataset?

**Comment by elenamer** [comment]
Hello,

Thanks for pointing that out! 

Yes, the iRhythmTestDataset ended up not being supported, because only the test set is publicly available.

Following are all supported datasets:

PTBXLDataset
CincChallenge2017Dataset
CPSC2018Dataset
Arr10000Dataset
MITBIHARDataset
LongTermAFDataset
INCARTDataset
AFDataset
MITBIHSVDataset
